version = "20221216"

rdpport="-p 3390:3389"
vncport="-p 5901:5901"
vncflag="--vnc"

[linux]
base="""sudo docker run \\
  --shm-size=1gb -it --privileged --name neurodesktop \\
  -v ~/neurodesktop-storage:/neurodesktop-storage \\
  -e HOST_UID="$(id -u)" -e HOST_GID="$(id -g)" \\
  -p 8080:8080"""

[windows]
base="""docker run \
--shm-size=1gb -it --privileged --name neurodesktop \
-v C:/neurodesktop-storage:/neurodesktop-storage \
-p 8080:8080"""
